name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    
    - name: Install dependencies
      run: ${{matrix.env}} bundle install
    
    - name: Preparing environment (ubuntu)
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt-get install postgresql postgresql-contrib
        echo "local all all trust" | sudo tee -a /var/lib/postgresql/12/main/pg_hba.conf
        sudo systemctl restart postgresql
        sudo -u postgres createuser -s -d $(id -un)
        sudo -u postgres createdb test
    
    - name: Preparing environment (macos)
      if: matrix.os == 'macos'
      run: brew install mariadb
    
    - name: Run tests
      timeout-minutes: 5
      run: |
        ${{matrix.env}} bundle exec rspec
